//
//  ProcedureTagDecoderTests.m
//  ProjectCrystalBlueOSX
//
//  Created by Logan Hood on 2/16/14.
//  Copyright (c) 2014 Project Crystal Blue. All rights reserved.
//

#import <XCTest/XCTest.h>
#import "ProcedureTagDecoder.h"
#import "ProcedureNameConstants.h"

@interface ProcedureTagDecoderTests : XCTestCase

@end

@implementation ProcedureTagDecoderTests

- (void)setUp
{
    [super setUp];
    // Put setup code here. This method is called before the invocation of each test method in the class.
}

- (void)tearDown
{
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}

/// Checks that comma separated tags are properly parsed.
- (void)testParseCommaSeparatedTags
{
    // First generate a list of ALL tags, comma separated.
    NSMutableString *commaSeparatedTags = [NSMutableString stringWithString:@""];
    for (NSString *tag in [ProcedureNameConstants allProcedureTags]) {
        if ([commaSeparatedTags isEqualToString:@""]) {
            [commaSeparatedTags appendFormat:@"%@", tag];
        } else {
            [commaSeparatedTags appendFormat:@"%@%@", TAG_DELIMITER, tag];
        }
    }
    
    NSArray *names = [ProcedureTagDecoder nameArrayFromTags:commaSeparatedTags];
    
    // We expect every name to be present in the final array.
    XCTAssertEqual(names.count, [ProcedureNameConstants allProcedureNames].count);
    
    for (NSString *name in [ProcedureNameConstants allProcedureNames]) {
        XCTAssertTrue([names containsObject:name], @"Decoded array didn't include %@", name);
    }
}

/// Tests the decoder handles custom tags properly ("custom" meaning a tag not predefined in ProcedureNameConstants).
- (void)testCustomTag
{
    NSString *CUSTOM_TAG01 = @"CSTM";
    NSString *expectedNameForCustomTag01 = [NSString stringWithFormat:PROC_NAME_CUSTOM, CUSTOM_TAG01];
    NSString *CUSTOM_TAG02 = @"ASDF";
    NSString *expectedNameForCustomTag02 = [NSString stringWithFormat:PROC_NAME_CUSTOM, CUSTOM_TAG02];
    
    // To test this behavior, we'll use a mix of custom and supported tags.
    NSString *commaSeparatedTags = [NSString stringWithFormat:@"%@%@%@%@%@%@%@",
                                    CUSTOM_TAG01,
                                    TAG_DELIMITER,
                                    PROC_TAG_BILLET,
                                    TAG_DELIMITER,
                                    CUSTOM_TAG02,
                                    TAG_DELIMITER,
                                    PROC_TAG_GEMINI_DOWN];
    
    NSArray *nameArray = [ProcedureTagDecoder nameArrayFromTags:commaSeparatedTags];
    
    XCTAssertEqualObjects([nameArray objectAtIndex:0], expectedNameForCustomTag01);
    XCTAssertEqualObjects([nameArray objectAtIndex:1], PROC_NAME_BILLET);
    XCTAssertEqualObjects([nameArray objectAtIndex:2], expectedNameForCustomTag02);
    XCTAssertEqualObjects([nameArray objectAtIndex:3], PROC_NAME_GEMINI_DOWN);
}

/// Checks that all the methods give expected results for empty string or empty array as args
- (void)testEmptyStringArguments
{
    NSArray *emptyArray = [[NSArray alloc] init];
    NSString *emptyString = @"";
    
    NSArray *nameArrayFromEmptyTagString = [ProcedureTagDecoder nameArrayFromTags:emptyString];
    XCTAssertEqualObjects(nameArrayFromEmptyTagString, emptyArray,
                          @"Actual array generated by nameArrayFromTags wasn't empty!");
    
    NSArray *tagArrayFromEmptyString = [ProcedureTagDecoder tagArrayFromCommaSeparatedTagString:emptyString];
    XCTAssertEqualObjects(tagArrayFromEmptyString, emptyArray,
                          @"Actual array generated by tagArrayFromCommaSeparatedTagString wasn't empty!");
    
    NSArray *nameArrayFromEmptyArray = [ProcedureTagDecoder nameArrayFromTagArray:emptyArray];
    XCTAssertEqualObjects(nameArrayFromEmptyArray, emptyArray,
                          @"Actual array generated by nameArrayFromTagArray wasn't empty!");
}

@end
